apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: activ3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-aplicacion
  template:
    metadata:
      labels:
        app: mi-aplicacion
    spec:
      containers:
      - name: mi-aplicacion
        image: ocap/actividad3-unir:app-v1.0.3
        ports:
        - containerPort: 8181