apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: activ3
spec:
  selector:
    app: mi-aplicacion
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
  type: LoadBalancer  # Esto hará que la aplicación sea accesible desde internet