apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: activ3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: ocap/actividad3-unir:db-v1.0.1
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-password
        ports:
        - containerPort: 3306